
import { Product, Category } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 'p-macbook-m4',
    name: 'MacBook Pro M4 Max 16"',
    nameAr: 'ماك بوك برو M4 ماكس ١٦ بوصة',
    price: 124950,
    oldPrice: 135000,
    category: 'Laptops',
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&q=85&w=1200',
    rating: 5,
    reviews: 124,
    isHot: true,
    isNew: true,
    description: '16-Core CPU, 40-Core GPU, and 128GB Unified Memory. The peak of 2026 mobile computing.',
    descriptionAr: 'معالج ١٦ نواة، ومعالج رسوميات ٤٠ نواة، وذاكرة موحدة ١٢٨ جيجابايت. قمة حوسبة ٢٠٢٦ المحمولة.'
  },
  {
    id: 'p-iphone-17',
    name: 'iPhone 17 Pro Max Titanium',
    nameAr: 'آيفون ١٧ برو ماكس تيتانيوم',
    price: 69950,
    oldPrice: 75000,
    category: 'Smartphones',
    image: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&q=85&w=1200',
    rating: 4.9,
    reviews: 450,
    isHot: true,
    isNew: true,
    description: 'Aerospace-grade titanium with A19 Pro Bionic architecture and holographic FaceTime.',
    descriptionAr: 'تيتانيوم من الدرجة الفضائية مع معمارية A19 Pro Bionic ودعم فيس تايم هولوغرافي.'
  },
  {
    id: 'p-iphone-15-pro',
    name: 'iPhone 16 Pro Titanium',
    nameAr: 'آيفون ١٦ برو تيتانيوم',
    price: 45000,
    category: 'Smartphones',
    image: 'https://images.unsplash.com/photo-1678652197831-2d180705cd2c?auto=format&fit=crop&q=85&w=1200',
    rating: 4.8,
    reviews: 1200,
    description: 'The latest titanium powerhouse with advanced triple camera system.',
    descriptionAr: 'أحدث قوة تيتانيوم مع نظام كاميرا ثلاثي متطور.'
  },
  {
    id: 'p-s24-ultra',
    name: 'Samsung Galaxy S24 Ultra',
    nameAr: 'سامسونج جالاكسي S24 الترا',
    price: 38000,
    category: 'Smartphones',
    image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&q=85&w=1200',
    rating: 4.7,
    reviews: 980,
    description: 'AI-integrated legacy flagship with 200MP camera and built-in S-Pen.',
    descriptionAr: 'هاتف رائد كلاسيكي متكامل مع الذكاء الاصطناعي، كاميرا ٢٠٠ ميجابكسل وقلم S-Pen مدمج.'
  },
  {
    id: 'p-macbook-air-m3',
    name: 'MacBook Air M3',
    nameAr: 'ماك بوك إير M3',
    price: 55000,
    category: 'Laptops',
    image: 'https://images.unsplash.com/photo-1611186871348-b1ec696e52c9?auto=format&fit=crop&q=85&w=1200',
    rating: 4.8,
    reviews: 560,
    description: 'Thin, light, and powerful with the M3 chip. Perfect for on-the-go productivity.',
    descriptionAr: 'نحيف، خفيف، وقوي مع شريحة M3. مثالي للإنتاجية أثناء التنقل.'
  },
  {
    id: 'p-sony-xm5',
    name: 'Sony WH-1000XM5',
    nameAr: 'سوني WH-1000XM5',
    price: 15000,
    category: 'Audio',
    image: 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?auto=format&fit=crop&q=85&w=1200',
    rating: 4.9,
    reviews: 2300,
    description: 'Industry-leading noise canceling and exceptional sound quality.',
    descriptionAr: 'إلغاء ضوضاء رائد في الصناعة وجودة صوت استثنائية.'
  },
  {
    id: 'p-razer-mouse',
    name: 'Gaming Mouse Razer',
    nameAr: 'ماوس ألعاب رايزر',
    price: 4500,
    category: 'Gaming',
    image: 'https://images.unsplash.com/photo-1527814050087-37a3c71cc2a5?auto=format&fit=crop&q=85&w=1200',
    rating: 4.6,
    reviews: 890,
    description: 'Precision gaming sensor with customizable Chroma RGB lighting.',
    descriptionAr: 'مستشعر ألعاب دقيق مع إضاءة Chroma RGB قابلة للتخصيص.'
  },
  {
    id: 'p-vision-pro-2',
    name: 'Apple Vision Pro 2',
    nameAr: 'آبل فيجن برو ٢',
    price: 95000,
    oldPrice: 110000,
    category: 'Wearables',
    image: 'https://images.unsplash.com/photo-1622979135225-d2ba269cf1ac?auto=format&fit=crop&q=85&w=1200',
    rating: 5,
    reviews: 56,
    isFlashSale: true,
    isHot: true,
    description: 'Unlock spatial computing. Ultra-HD micro-OLED displays with 16K resolution per eye.',
    descriptionAr: 'افتح آفاق الحوسبة المكانية. شاشات micro-OLED بدقة 16K لكل عين.'
  },
  {
    id: 'p-rtx-5090',
    name: 'RTX 5090 Gaming Beast',
    nameAr: 'RTX 5090 وحش الألعاب',
    price: 145000,
    oldPrice: 174000,
    category: 'Gaming',
    image: 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&q=85&w=1200',
    rating: 5,
    reviews: 89,
    isHot: true,
    isFlashSale: true,
    description: 'Liquid-cooled Blackwell architecture with 32GB VRAM. 8K gaming redefined.',
    descriptionAr: 'معمارية Blackwell المبردة سائلًا مع ٣٢ جيجابايت VRAM. إعادة تعريف ألعاب 8K.'
  },
  {
    id: 'p-sony-xm7',
    name: 'Sony WH-1000XM7 Pro',
    nameAr: 'سوني WH-1000XM7 برو',
    price: 12500,
    oldPrice: 15500,
    category: 'Audio',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&q=85&w=1200',
    rating: 4.9,
    reviews: 145,
    isFlashSale: true,
    description: 'Spatial 8K audio with adaptive neuro-canceling technology.',
    descriptionAr: 'صوت مكاني 8K مع تقنية إلغاء الضوضاء العصبية المتكيفة.'
  },
  {
    id: 'p-airpods-max-2',
    name: 'AirPods Max 2 Ultra',
    nameAr: 'آيربودز ماكس ٢ الترا',
    price: 18500,
    oldPrice: 22000,
    category: 'Audio',
    image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&q=85&w=1200',
    rating: 4.8,
    reviews: 210,
    isNew: true,
    isFlashSale: true,
    description: 'H4 Neural chip with 120 hours of spatial audio battery life.',
    descriptionAr: 'شريحة H4 العصبية مع بطارية تدوم ١٢٠ ساعة من الصوت المكاني.'
  },
  {
    id: 'p-fold-8',
    name: 'Samsung Galaxy Z Fold 8',
    nameAr: 'سامسونج جالاكسي Z فولد ٨',
    price: 85000,
    oldPrice: 95000,
    category: 'Smartphones',
    image: 'https://images.unsplash.com/photo-1592890288564-76628a30a657?auto=format&fit=crop&q=85&w=1200',
    rating: 4.7,
    reviews: 156,
    isHot: true,
    isFlashSale: true,
    description: 'Triple-fold infinity display with integrated S-Pen Pro 4.',
    descriptionAr: 'شاشة إنفينيتي ثلاثية الطي مع قلم S-Pen Pro 4 المدمج.'
  },
  {
    id: 'p-mavic-5',
    name: 'DJI Mavic 5 Pro Drone',
    nameAr: 'طائرة DJI Mavic 5 Pro بدون طيار',
    price: 45000,
    oldPrice: 52000,
    category: 'Eco-Tech',
    image: 'https://images.unsplash.com/photo-1473968512647-3e44a224fe8f?auto=format&fit=crop&q=85&w=1200',
    rating: 4.9,
    reviews: 88,
    isHot: true,
    isNew: true,
    description: '8K 120FPS Hasselblad camera with 60-minute flight time and satellite link.',
    descriptionAr: 'كاميرا Hasselblad بدقة 8K و١٢٠ إطاراً في الثانية مع وقت طيران ٦٠ دقيقة ورابط قمر صناعي.'
  }
];

export const CATEGORIES: Category[] = [
  { id: 'smartphones', name: 'Smartphones', nameAr: 'الهواتف الذكية', icon: '📱', subcategories: ['Apple', 'Samsung', 'Xiaomi'] },
  { id: 'laptops', name: 'Laptops', nameAr: 'اللابتوبات', icon: '💻', subcategories: ['MacBook', 'Gaming', 'Office'] },
  { id: 'gaming', name: 'Gaming', nameAr: 'الألعاب', icon: '🎮', subcategories: ['Consoles', 'PC Gear'] },
  { id: 'wearables', name: 'Wearables', nameAr: 'الإلكترونيات القابلة للارتداء', icon: '⌚', subcategories: ['Watch', 'Glasses'] },
  { id: 'audio', name: 'Audio', nameAr: 'الصوتيات', icon: '🎧', subcategories: ['Headphones', 'Earbuds'] },
  { id: 'eco', name: 'Eco-Tech', nameAr: 'التكنولوجيا الصديقة للبيئة', icon: '🌿', subcategories: ['Solar', 'Recycled'] },
];
